# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = true

# A continuation prompt that displays two filled in arrows
continuation_prompt = "â–¶â–¶"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Set "austin" as custom color palette
palette = "austin"

format = """$time$username $fill$cmd_duration$status
$directory
$os$shell$character"""

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled = false

# Define custom colors
[palettes.austin]
neon_green = "#39FF14"

[os]
format = "[ $symbol ]($style)"
style = "bold white"
disabled = false

# This is the default symbols table.
[os.symbols]
Alpaquita = "ğŸ””"
Alpine = "ğŸ”ï¸"
Amazon = "ğŸ™‚"
Android = "ğŸ¤–"
Arch = "ğŸ—ï¸"
Artix = "ğŸ—ï¸"
CentOS = "ğŸ’ "
Debian = "ğŸŒ€"
DragonFly = "ğŸ‰"
Emscripten = "ğŸ”—"
EndeavourOS = "ğŸš€"
Fedora = "ğŸ©"
FreeBSD = "ğŸ˜ˆ"
Garuda = "ğŸ¦…"
Gentoo = "ğŸ—œï¸"
HardenedBSD = "ğŸ›¡ï¸"
Illumos = "ğŸ¦"
Linux = "ğŸ§"
Mabox = "ğŸ“¦"
Macos = "ğŸ"
Manjaro = "ğŸ¥­"
Mariner = "ğŸŒŠ"
MidnightBSD = "ğŸŒ˜"
Mint = "ğŸŒ¿"
NetBSD = "ğŸš©"
NixOS = "â„ï¸"
OpenBSD = "ğŸ¡"
OpenCloudOS = "â˜ï¸"
openEuler = "ğŸ¦‰"
openSUSE = "ğŸ¦"
OracleLinux = "ğŸ¦´"
Pop = "ğŸ­"
Raspbian = "ğŸ“"
Redhat = "ğŸ©"
RedHatEnterprise = "ğŸ©"
Redox = "ğŸ§ª"
Solus = "â›µ"
SUSE = "ğŸ¦"
Ubuntu = "ğŸ¯"
Unknown = "â“"
# Windows = "ğŸªŸ"
Windows = "îœ"

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
format = "[ \[$user\] ]($style)"
style_user = "bg:#f07623 fg:#ffffff"
style_root = "bg:#93d0fc fg:#fe0000"

[time]
time_format = "%A|%d-%b-%Y|%T|%:z"
format = "[ \[$timeğŸ•™\] ]($style)"
style = "bg:#00a1de fg:#ffffff"
disabled = false

[shell]
format = "[$indicator]($style)"
powershell_indicator = "î¯‡ "
cmd_indicator = "î¯„ "
disabled = false

[fill]
symbol = "-"
style = "fg:neon_green"
disabled = false

[cmd_duration]
min_time = 1
show_milliseconds = true
disabled = false
format = " [$duration ]($style)"

[status]
symbol = " ğŸ”´ "
success_symbol = " ğŸŸ¢ "
format = "[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) "
map_symbol = true
disabled = false

[directory]
format = "[ $path ]($style)"
style = "bg:#9600ff fg:#0bff01"
truncation_length = 3
truncation_symbol = "â€¦\\"
use_os_path_sep = true
home_symbol = "~"

# Here is how you can shorten some long paths by text replacement
# Similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ğŸ“„ "
"Downloads" = "ğŸ“¥ "
"Music" = "ğŸœ "
"Pictures" = "ğŸ“· "

# Replace the "â¯" symbol in the prompt with "âœ"
# The name of the module we are configuring is "character"
[character] 
# The "success_symbol" segment is being set to "âœ" with the color "bold green"
success_symbol = "[âœ](bold green)" 
error_symbol = "[âœ—](bold red)"

[python]
symbol = "ğŸ "
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"
format = "via [${symbol}python (${version} )(\($virtualenv\) )]($style)"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[hostname]
ssh_only = true
format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
disabled = false

[localip]
ssh_only = true
format = "@[$localipv4](bold red) "
disabled = false

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
disabled = false

